### ISSUE TITLE
Add .idea to gitignore file

### ISSUE THREAD

**Issue by alifzl** [fardaar/Learning-Deep-Reinforcement-Learning#1]
adding .idea files to the repository is not necessary. you can omit it by adding it to the gitignore file.

**Comment by fardaar** [comment]
what he fuck is gitignore? and what the fuck is .idea?

**Comment by AFZL95** [comment]
read [this](https://guide.freecodecamp.org/git/gitignore/) young man

**Comment by fardaar** [comment]
Thank you Sensei

**Comment by alifzl** [comment]
probably you don't want to do this thing. so I'm closing it :))
